version: "3.8"
services:
  HubService:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  ChromeService:
    image: selenium/node-chrome:latest
    shm_size: "2g"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=2
    depends_on:
      - HubService

  FirefoxService:
    image: selenium/node-firefox:latest
    shm_size: "2g"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=2
    depends_on:
      - HubService

  EdgeService:
    image: selenium/node-edge:latest
    shm_size: "2g"
    ports:
      - "5900"
      - "7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=2
    depends_on:
      - HubService

  ChromeVideo:
    image: selenium/video:latest
    volumes:
    - ./test-output/videos:/videos
    depends_on:
        - ChromeService
    environment:
      - DISPLAY_CONTAINER_NAME=ChromeService
      - FILE_NAME=seleniumGridChromeDocker.mp4